jobs:
  build:
    runs-on: "${{ matrix.os }}"
    steps:
    - uses: "actions/checkout@v3"
      with:
        submodules: true
    - uses: "actions/setup-dotnet@v2"
      with:
        global-json-file: "global.json"
    - run: "dotnet restore"
    strategy:
      matrix:
        os: [
          "macos-10.15",
          "macos-11",
          "macos-12",
          "ubuntu-16.04",
          "ubuntu-18.04",
          "ubuntu-20.04",
          "ubuntu-22.04",
          "windows-2019",
          "windows-2022"
        ]
on: [
  "push"
]
