name: Main workflow
on: [push]
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    - run: dotnet tool restore
    - run: dotnet format --check --dry-run
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    - run: dotnet restore
    - run: dotnet build
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    - run: dotnet restore
    - run: dotnet build
    - run: dotnet test
