name: Main workflow
on: [push]
jobs:
  check-build-test:
    name: Check-Build-Test
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: "3.1.201"
    - run: dotnet tool restore
    #- run: dotnet format --check --dry-run  
    - run: dotnet clean
    - run: dotnet restore
    - run: dotnet build
    - run: dotnet test
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest]
