name: Main workflow
on: [push]
jobs:
  check-build-test:
    name: Check-Build-Test
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - run: dotnet tool restore
    #- run: dotnet format --check --dry-run  
    - run: dotnet restore
    - run: dotnet build
    - run: dotnet test
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest]
