name: Main workflow
on: [push]
jobs:
  check-build-test:
    name: Check-Build-Test
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "3.1.302"
    - run: dotnet tool restore
    - run: dotnet format --check  
    - run: dotnet restore
    - run: dotnet build
    - run: dotnet test
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]
